apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
        - name: blog-api-container
          image: localhost:5000/yohaido159/blog_image:v7
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: blog-api-service
spec:
  type: NodePort
  selector:
    app: blog-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 31515
